### PR TITLE
Poking around

### PR DESCRIPTION
**Pull request by darrencauthon**
No need to merge, just showing

### CODE REVIEW

**Comment by LeamHall** [comment]
Darren, thanks!

On Thu, May 21, 2015 at 4:10 PM, Darren Cauthon <notifications@github.com>
wrote:

> No need to merge, just showing
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/LeamHall/SecComFrame/pull/7
> Commit Summary
>
>    - Different way to declare hashes.
>
> File Changes
>
>    - *M* tools/stig_munger/vuln_info.rb
>    <https://github.com/LeamHall/SecComFrame/pull/7/files#diff-0> (13)
>
> Patch Links:
>
>    - https://github.com/LeamHall/SecComFrame/pull/7.patch
>    - https://github.com/LeamHall/SecComFrame/pull/7.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/LeamHall/SecComFrame/pull/7>.
>



-- 
Mind on a Mission <http://leamhall.blogspot.com/>

**Comment by darrencauthon** [comment]
Sure, np...

If you don't mind me asking, what would you call the name of this ruby library?  What's the primary way it is meant to be used?

**Comment by darrencauthon** [comment]
I ask just because I'd like to show you one thing with regarding to organizing the code.

**Comment by LeamHall** [comment]
You're always welcome to ask. Doesn't mean I know the answer, though.  :)

So there's a plan for a datastore of security vulnerabilities. One of the
measurement documents is in malformed XML, that stig_cleaner.rb tries to
handle. This small collection of code should be able to take a data source,
ingest it, and then populate the data store.

Another script I need to write will allow modifying individual datastore
items. Haven't gotten there yet.

That make sense? I'm aware of the concept of libraries, but my skills
aren't there yet.

Thanks!

Leam


On Thu, May 21, 2015 at 4:22 PM, Darren Cauthon <notifications@github.com>
wrote:

> I ask just because I'd like to show you one thing with regarding to
> organizing the code.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/LeamHall/SecComFrame/pull/7#issuecomment-104410526>.
>



-- 
Mind on a Mission <http://leamhall.blogspot.com/>

**Comment by darrencauthon** [comment]
That makes sense.  Would you call it "STIG" if you had to name it?

Sounds like this will be a set of command-line scripts to run?

**Comment by LeamHall** [comment]
Very much command line scripts. At the moment I just call it "stig munger"
because it's to convert the STIG to a useful format.

On Thu, May 21, 2015 at 4:32 PM, Darren Cauthon <notifications@github.com>
wrote:

> That makes sense. Would you call it "STIG" if you had to name it?
>
> Sounds like this will be a set of command-line scripts to run?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/LeamHall/SecComFrame/pull/7#issuecomment-104412967>.
>



-- 
Mind on a Mission <http://leamhall.blogspot.com/>

**Comment by darrencauthon** [comment]
Cool. I'll have a few other suggestions soon...



—

**Comment by LeamHall** [comment]
ruby -v
ruby 1.8.7 (2013-06-27 patchlevel 374) [x86_64-linux]

CentOS 6. Part of the driver is the "target market". This is the latest Ruby most of them will have access to.

**Comment by darrencauthon** [comment]
Ah, that takes the fun out of it.  My thoughts was to show you how to organize this code into a single gem.  Gems can also include executable scripts, so for the price of moving the files into the appropriate folders you'd have a working gem.

However, if you're on 1.8.7 I'm not going to do that, just because I don't know what issues I'd hit.  I have to warn you:  I'm pretty sure that official maintenance has ended for 1.8.7, including security patches.  My advice is to upgrade to 1.9.3 or higher, preferably to 2.0+ if possible.

**Comment by darrencauthon** [comment]
ruby 1.8.7 required =>

1.9.3 added support for the : syntax

**Pull request closed without merging**
